### PR TITLE
Model support for /data_static

### PR DESCRIPTION
**Pull request by FosterZRussian**
**Practical purpose:**
Achieves more convenient and self-contained file placement. Making an addon with huge amount of assets like playermodels would allow you to store those in one easy to reach location.

### CODE REVIEW

**Comment by robotboy655** [comment]
Put the models into the `models/` folder.

**Comment by FosterZRussian** [comment]
What kind of a security risk do models pose to stand out from other assets? Placing them in an another path due to arbitrary restrictions only adds more difficulty to file management, where a potential player could easily lose track of what to clean up and where (since you can't purge data files using a ConVar like .gmas)

**Comment by robotboy655** [comment]
There's no security concerns here, just a logical ones. Why have 2 separate places for the exact same purpose?

> Placing them in an another path due to arbitrary restrictions only adds more difficulty to file management,  where a potential player could easily lose track of what to clean up and where 

I am really not sure what you are getting at here. Placing them in another path is what you are asking for, but you have not provided a logical reason why they should be there. Or any reason for that matter.

I am also not sure what you mean by "lose track of what to clean up and where" in related to Workshop Addons, end user doesn't even need to worry about it, it is handled for them by Steam. And your proposed changes do not affect this in any way whatsoever.

On the point of "why restrict this", in addition to the aforementioned reasoning, the other reason to restrict this is for the game to easily pickup the models for the addon in the spawnmenu automatically (Browse > Addons), so the player can easily access them.

**Comment by FosterZRussian** [comment]
I don't think it's difficult to implement data_static paths for Spawn menu, because it's not about saving models via file.Write and potentially this change could have a big impact on the community. 

It would just help solve a lot of problems for different developers, for example: 
- More convenient and, most importantly, faster management of game resources from the point of view of development due to the hierarchy necessary for developers. 
- It is easier for developers to work with game files, combining experience from non-proprietary game engines (due to the possibility of implementing similar directory behavior).
- Addons file locations will have a single hierarchy from the moment of development to the publication of content, which eliminates cases of loss of unnecessary content, since all management is in a convenient format.
- Simplifies porting content from different games\engines\ editors, including allows you to build a complete content automation process, for example, exporting content from a 3d editor/games directly to the target custom directory of the addons, immediately with sounds \ textures, etc.
- Allows you to almost completely implement any hierarchy of directories using /data_static/ for game modes or addons, for target content, without logical-garbage.

In the end, Garry's Mod will have more features, especially since it is already possible to save other file types in the data_static directory, and why not just give players the last piece for this system.

**Pull request closed without merging**
